# Generated by Django 3.0.6 on 2020-05-26 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_status', models.CharField(choices=[('C', 'Completed'), ('Ip', 'InProgress'), ('P', 'Pending')], default='P', max_length=20)),
                ('staff_handling', models.CharField(default='select staff', max_length=300)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(default='media/README', null=True, upload_to='clientfiles/')),
                ('file_name', models.CharField(default='file name', max_length=300)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
        ),
    ]
