# Generated by Django 2.2.12 on 2020-05-18 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.TimeField(null=True)),
                ('project_status', models.CharField(blank=True, choices=[('C', 'Completed'), ('Ip', 'InProgress'), ('P', 'Pending')], max_length=1)),
                ('staff_handling', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('file_path', models.CharField(max_length=300)),
                ('upload_date', models.CharField(max_length=300)),
                ('project_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
        ),
    ]
