# Generated by Django 2.2.12 on 2020-05-18 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='time',
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_status',
            field=models.CharField(choices=[('C', 'Completed'), ('Ip', 'InProgress'), ('P', 'Pending')], default='Pending', max_length=1),
        ),
        migrations.AlterField(
            model_name='projects',
            name='staff_handling',
            field=models.CharField(default='select staff', max_length=300),
        ),
    ]
