# Generated by Django 3.0.3 on 2021-08-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_upload',
            field=models.FileField(default='media/README', null=True, upload_to='clientfiles'),
        ),
    ]
