# Generated by Django 2.2.12 on 2020-05-18 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200518_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
