# Generated by Django 2.2.12 on 2020-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200518_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_status',
            field=models.CharField(choices=[('C', 'Completed'), ('Ip', 'InProgress'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
