# Generated by Django 2.2.12 on 2020-05-18 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200518_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.CharField(default='file name', max_length=300),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_path',
            field=models.CharField(default='file path', max_length=300),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
