# Generated by Django 2.2.12 on 2020-05-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200518_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_path',
        ),
        migrations.AddField(
            model_name='files',
            name='files',
            field=models.FileField(default='media/README', upload_to='clientfiles/'),
        ),
    ]
