# Generated by Django 3.0.6 on 2020-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projects_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.ImageField(default='media/README', null=True, upload_to='clientfiles'),
        ),
    ]
