# Generated by Django 3.0.6 on 2020-05-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200523_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='files',
        ),
        migrations.AddField(
            model_name='files',
            name='file_upload',
            field=models.FileField(default='media/README', null=True, upload_to='clientfiles/'),
        ),
    ]
